FROM python:3.11-slim
WORKDIR /mlflow
RUN pip install mlflow
EXPOSE 5000

CMD ["mlflow", "server", "--backend-store-uri", "sqlite:///mlflow/db/mlflow.db", "--artifacts-destination", "/mlflow/artifacts", "--default-artifact-root", "/mlflow/artifacts", "--host", "0.0.0.0", "--port", "5000"]