FROM python:3.11-slim
WORKDIR /mlflow
RUN pip install mlflow psycopg2-binary boto3
EXPOSE 5000

# CMD ["mlflow", "server", "--backend-store-uri", "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}", "--artifacts-destination", "s3://mlflow/artifacts", "--default-artifact-root", "/mlflow/artifacts", "--host", "0.0.0.0", "--port", "5000"]